### ISSUE TITLE
Update "find or create" to "find" in services 

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#344]
As per my understanding, If any application is requesting to subscribe an application, that should be already registered in RegistryOffice. 
So, when RegistryOffice is receiving any request for subscribing like /v1/notify-approvals, if it is already registered, the requesting application's data will be processed further (like creating instances in LTP and FC). 

Problem statement:
In requests like _/v1/notify-deregistrations, /v1/notify-approvals and /v1/notify-withdrawn-approvals_, we have attribute called "subscriber-application". This attribute has a description "_find or create_". This will create a new application if it is not already available in logical-termination-point list. 

Solution:
If my above understanding is correct, shall we update the descriptions of "subscriber-application" of  _/v1/notify-deregistrations, /v1/notify-approvals and /v1/notify-withdrawn-approvals_, from "_find or create_" to "_**find**_". 
This will enable us creating subscriptions only for already registered applications. 
Kindly let me know your views.

**Comment by openBackhaul** [comment]
>
>So, when RegistryOffice is receiving any request for subscribing like /v1/notify-approvals, if it is already registered,
>
Yes, that's right. At the time some application is subscribing at the RO, the RO already has HttpClient and TcpClient of this application. (The OperationClient might be missing and would have to be created.)

But this is an exceptional case, caused by all applications registering at the RO first.
In general, the characteristic element of a Subscription is that HttpClient and TcpClient might be created.

I would like to stick with the general practice of translating a forwarding of type Subscription into "find and create".
In case of RO, this just means that the HttpClient and TcpClient will always the found and never be created.

If you would share the view, please just close the issue.
Otherwise, please indicate the benefit of changing and assign back to me.

**Comment by IswaryaaS** [comment]
Thanks for explaining me the expectation and I agree with your point that "in general practice, subscriptions would allow creating new instances in an application"

- But I got this question based on the ultimate goal of introducing RegistryOffice into architecture, where we have RegistryOffice to avoid anonymous applications to access the resource of the architecture. 
- Having "find or create" in these subscriptions would allow any anonymous subscriptions to create HttpClient, TcpClients and OperationClients. Once subscribed, further registrations will be notified to the anonymous applications. 
- On the other hand, since the anonymous application would not have been gone through registration process, the application would not have regarded to OperationKeyManagement or ApplicationLayerTopology. Because of this, operation-key update would not happen in OperationClients of RO. All the transactions can happen through a default operation-key which we create while creating op-c instance. so here the security would be a question as well. 

Kindly let me know your views or please correct me if I am wrong.

**Comment by openBackhaul** [comment]
I would like to stick with the general practice of translating a forwarding of type Subscription into "find or create".
Security of the RO, respectively the architecture shall be assured by the management of operation keys.

I would rather spend efforts into getting the management of operation keys to work than into exceptions from general concepts.

If you would share the view, please just close the issue.
Otherwise, please indicate the benefit of changing and assign back to me.

**Comment by IswaryaaS** [comment]
Thanks for the letting me understand the expectation. Hence closing the issue
