### ISSUE TITLE
/v1/notify-withdrawn-approvals :: request notified? :: testcase fails  always

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#480]
testcase fails
- [x] /v1/notify-withdrawn-approvals :: request notified?
- [x] /v1/regard-updated-approval-status :: Forwardings triggered? :: Approval Notification
- [x] /v1/regard-updated-approval-status :: Forwardings triggered? ::  WithdrawnApprovalNotification

**Comment by PrathibaJee** [comment]
**Assertion failure details**
In RO Individual Services , following are the assertions that are failed because of this problem, 

1. /v1/list-applications:: Response body completeness - Count 2
Reason :
As list-applications will list all the registered-applications and not only approved applications in test suite we need to fetch the application from forwarding TypeApprovalCausesRequestForEmbedding and compare.
2. /v1/notify-withdrawn-approvals:: Request notified?
Reason : 
While getting the condition for assertion operation-name is fetched incorrectly 
3. /v1/regard-updated-approval-status:: Forwardings triggered? / ApprovalNotification
4. /v1/regard-updated-approval-status:: Forwardings triggered? / WithdrawnApprovalNotification
5. /v1/regard-updated-approval-status:: Delete fc-port notified? / ServerReplacementBroadcast and OperationUpdateBroadcast
Reason for 3 to 5  :
While comparing with the trace indicator it is being compared with the exact value instead of includes.
