### ISSUE TITLE
ALT shall be excluded while choosing request-body in testcases

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#486]
In services like /v1/notify-deregistrations, /v1/notify-approvals, /v1/notify-withdrawn-approvals, a random application is chosen for forming request body. Testcases like Update LTP notified? rareley fails when ALT is chosen as http-c to form request-body. 

Because, when ALT is chosen, the callback sent to ALT is failed with 404 when ip-address or port information is updated and tested. 

In order to avoid this testcase failure, ApplicationLayerTopology application's http-c could be avoided while choosing random application for request body

**Comment by PrathibaJee** [comment]
**Assertion failure details**
In RO Individual Services , following are the assertions that are failed because of this problem, 
/v1/notify-approvals :: Update LTP notified? / subscriber-address update / ipv-4-address update
/v1/notify-approvals :: Update LTP notified? / subscriber-port update
/v1/notify-deregistrations::Update LTP notified? / subscriber-address update / ipv-4-address update

Reason  :
As part of the request ALT application ip-address is being updated ,due to which update-ltp is not being sent to ALT . So , from test-suite for update-ltp testcases we should avoid ALT application while formulating request.
