### ISSUE TITLE
/v1/regard-updated-approval-status:: Update FC notified? / ServerReplacementBroadcast and OperationUpdateBroadcast test cases failing 

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/RegistryOffice#487]
**Issue Description**: 
When we execute /v1/regard-updated-approval-status for newly registered application with approval status as  **APPROVED** .

The forwarding constructs ServerReplacementBroadcast and OperationUpdateBroadcast will be updated with the operation-clients of the registered application and update-fc call back will be sent to ALT which is being failed with Internal server Error .

**Observation**:
As part of update-fc execution  ALT will update RO's forwarding construct which is present as part of it's application data.

The update-fc callback which is sent to ALT is returning 204 response-code and we can observe the change in the application data of   ALT . But , in RO application it is returning 500 INTERNAL SERVER ERROR.

>Priority:Medium;
>AffectedFlow:Approval Process/RO : /v1/regard-updated-approval-status;

**Comment by PrathibaJee** [comment]
**Assertion failure details**
In RO Individual Services , following are the assertions that are failed because of this problem, 
/v1/regard-updated-approval-status:: Update FC notified? / ServerReplacementBroadcast and OperationUpdateBroadcast

Reason  :
As part of update-fc execution ALT will update RO's forwarding construct which is present as part of it's application data.
The update-fc callback which is sent to ALT is returning 204 response-code and we can observe the change in the application data of ALT . But , in RO application it is returning 500 INTERNAL SERVER ERROR.
