### ISSUE TITLE
RO/v1/deregister-application does not call ALT/v1/delete-ltp-and-dependents

### ISSUE THREAD

**Issue by MartinSunal** [openBackhaul/RegistryOffice#99]
Problem:

when RO/v1/deregister-application is invoked then it calls ALT/v1/update-ltp.
However, it should call ALT/v1/delete-ltp-and-dependents based on load file forwarding ServiceRequestCausesLtpDeletionRequest.

**Comment by MartinSunal** [comment]
I also noticed that ALT/v1/delete-fc-port is not called during RO/v1/deregister-application.
I think it is because load file forwarding ServiceRequestCausesFcPortDeletionRequest does not contain input fc-port with ro-0-0-1-op-s-3002 (v1/deregister-application).
Is it desired? or a bug?

**Comment by openBackhaul** [comment]
This issue seems to be wrongly assigned.
Checked ForwardingList and CONFIGfile: 
- /v1/deregister-application is invoking ALT/v1/delete-ltp-and-dependents, which seem to be correct.

Might it be possible that this issue describes some fault in the implementation and needs to be assigned to the person who implemented the RO?

**Comment by openBackhaul** [comment]
I am referencing the [question in the comment from 24th of August](https://github.com/openBackhaul/RegistryOffice/issues/99#issuecomment-1225569971):
- If _RO/v1/deregister-application_ is calling _ALT/v1/delete-ltp-and-dependents_, not just the LTPs, but also the FcPorts, which are referencing the LTPs, shall be deleted.
- So, it is not necessary to additionally call _ALT/v1/delete-fc-port_ for deleting the FcPorts.

**Comment by MartinSunal** [comment]
closing based on clarification in last comment
